### ISSUE TITLE
Marked as a virus by 14 / 71 on virus total 🤔

### ISSUE THREAD

**Issue by techhotspot** [Zebratic/CSharpGUI#1]
Can you explain why this is marked as a trojan by a bunch of avs?

https://www.virustotal.com/gui/file/11f87a759ab9bcfb3f216696be2cb0021f9a2a685d656cf9e870c550a594d8a7/details

**Comment by Zebratic** [comment]
That's not even CSharpGUI, that's a different exe. 🤦‍♂️
